### ISSUE TITLE
Installation Build Caffe and pycaffe

### ISSUE THREAD

**Issue by CatOneTwo** [bigvideoresearch/OIM#4]
Hi, author.

Can you explain how to build Caffe and pycaffe in directory caffe-oim?

when I run the command " make all -j" produces the following error :

In file included from .build_release/src/caffe/proto/caffe.pb.cc:4:0:
.build_release/src/caffe/proto/caffe.pb.h:46:51: error: \u2018AuxiliaryParseTableField\u2019 in namespace \u2018google::protobuf::internal\u2019 does not name a type
   static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
                                                   ^
Makefile:582: recipe for target '.build_release/src/caffe/proto/caffe.pb.o' failed
make: *** [.build_release/src/caffe/proto/caffe.pb.o] Error 1
make: *** Waiting for unfinished jobs....

and how to following the Caffe installation instructions? which protobuf version were you used?

**Comment by sisrfeng** [comment]
Hi, have you solved it?

**Comment by CatOneTwo** [comment]
No ::>_<::
